### PR TITLE
Update trip requests to reflect now-required parameters

### PR DESCRIPTION
**Pull request by dotMorten**
`started_at__lte`, `started_at__gte` and `vehicle` are now required parameters when requesting a trip. If you don't provide these, you'll get a `401 Unauthorized` error.

Note that this is a recent change to Automatic's REST API, and their documentation hasn't been updated yet (confirmed by support).

### CODE REVIEW

**Comment by supergibbs** [comment]
Hi @dotMorten, can you pull in master and resolve this conflict? Thanks for all your contributions!!

**Comment by dotMorten** [comment]
@supergibbs Done!

**Comment by supergibbs** [comment]
Great thanks! I'll try to get a new build on nuget this weekend

**Comment by dotMorten** [comment]
No rush for my sake. I'm using my local clone :)

**Pull request merged**
